// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	TestDialogue = 0,
	Dish_Test = 1,
	Book_Test = 2,
	Chamber_Test = 3,
}
